In [1]:
import pandas as pd

In [2]:
import random

In [3]:
# 1. Definimos la cantidad de filas 
cantidad = 1000000

In [4]:
# 2. Conjunto de datos base reales
influencers_pool = ["@travel_veracruz", "@playa_MX", "@mexico_explorar", "@vida_estilo", "@paraiso_semanal", "@cancun_vacaciones"]
tipos_post_pool = ["foto", "video", "reel", "carrusel"]
fechas_pool = ["2026-05-01", "2026-05-10", "2026-05-15", "2026-05-20", "2026-05-24"]

In [9]:
# 3. Creación del DataFrame de 1,000,000 de registros usando comprensión de listas
df_instagram = pd.DataFrame({
    "influencer": [random.choice(influencers_pool) for _ in range(cantidad)],
    "likes": [random.randint(100, 50000) for _ in range(cantidad)],  # Rango de likes realista
    "comentarios": [random.randint(5, 2500) for _ in range(cantidad)],  # Rango de comentarios realista
    "fecha": [random.choice(fechas_pool) for _ in range(cantidad)],
    "tipo_post": [random.choice(tipos_post_pool) for _ in range(cantidad)]
})

In [10]:
# Definimos la cantidad (1 millón de registros)
cantidad = 1000000

In [11]:
df_instagram.shape

(1000000, 5)

In [12]:
df_instagram.dtypes

influencer       str
likes          int64
comentarios    int64
fecha            str
tipo_post        str
dtype: object

In [13]:
df_instagram.head()

           influencer  likes  comentarios       fecha tipo_post
0    @paraiso_semanal  37087          613  2026-05-01     video
1        @vida_estilo   2630         1830  2026-05-20      foto
2  @cancun_vacaciones  41660          611  2026-05-20      reel
3    @paraiso_semanal  36865         2378  2026-05-20      foto
4           @playa_MX  32525         2409  2026-05-20      reel

In [14]:
df_instagram.memory_usage(deep=True).sum() / (1024**2)

np.float64(206.71288871765137)

In [15]:
print("Promedio de Likes:", df_instagram["likes"].mean())
print("Promedio de Comentarios:", df_instagram["comentarios"].mean())

Promedio de Likes: 25034.203483
Promedio de Comentarios: 1252.864489

In [16]:
df_instagram.groupby("tipo_post")[["likes", "comentarios"]].mean()

                  likes  comentarios
tipo_post
carrusel   25053.507966  1253.683133
foto       25009.499962  1251.964847
reel       25028.773438  1253.142452
video      25044.994092  1252.667103

In [18]:
df_instagram.groupby("influencer")["likes"].sum().sort_values(ascending=False)

influencer
@cancun_vacaciones    4183754534
@mexico_explorar      4179759891
@paraiso_semanal      4175775084
@playa_MX             4170064722
@vida_estilo          4164326831
@travel_veracruz      4160522421
Name: likes, dtype: int64